Add image compression module
LitoMore/fanfou-pro pull request #4
Opened 2020-06-18 10:04 UTC by twoheartliu

2020-06-18 10:06 UTC, LitoMore commented on src/components/post-form.js
> +import {fileToBase64ByQuality, convertBase64UrlToBlob} from '../utils/image-compression';
```suggestion
import {fileToBase64ByQuality, convertBase64UrlToBlob} from '../utils/image-compression';

```

2020-06-18 10:13 UTC, LitoMore requested changes

2020-06-18 10:13 UTC, LitoMore commented on src/components/post-form.js
> +import {fileToBase64ByQuality, convertBase64UrlToBlob} from '../utils/image-compression';
An empty line required.

```suggestion
import {fileToBase64ByQuality, convertBase64UrlToBlob} from '../utils/image-compression';

```

2020-06-18 10:13 UTC, LitoMore commented on src/components/post-form.js
> +		console.log(files[0]);
Remove this `console.log`.

```suggestion
```

2020-06-18 10:13 UTC, LitoMore commented on src/utils/image-compression.js
> +//  图片最大宽度
Do not leave any Chinese comment.

2020-06-18 10:13 UTC, LitoMore commented on src/utils/image-compression.js
> +		// 图片偏移值
Ditto. Use English.

2020-06-18 10:13 UTC, LitoMore commented on src/utils/image-compression.js
> +		// const offetX = 0;
Remove this unused code.

2020-06-18 10:13 UTC, LitoMore commented on src/utils/image-compression.js
> +				// Const offetX = (img.width - MAX_WIDTH) / 2;
Ditto.

2020-06-18 10:13 UTC, LitoMore commented on src/utils/image-compression.js
> +	console.log('mimeType', mimeType);
Remove this.
```suggestion
```

2020-06-18 10:13 UTC, LitoMore commented on src/components/post-form.js
> +						console.log(result_blob);
Remove this.

```suggestion
```

2020-06-19 16:02 UTC, LitoMore requested changes

2020-06-19 16:02 UTC, LitoMore commented on src/utils/image-compression.js
> +	console.log(_blob);
Do not commit any `console.log`.

2020-06-19 16:02 UTC, LitoMore commented on src/components/post-form.js
>  		}
Too much if-else, please optimize your code.

2020-06-22 10:31 UTC, twoheartliu commented
Fixed above problem and add jump to image url

2020-07-19 12:56 UTC, LitoMore requested changes

2020-07-19 12:56 UTC, LitoMore commented on src/utils/image-compression.js
> +// Setting compression max width
Remove  this comment

2020-07-19 12:56 UTC, LitoMore commented on src/utils/image-compression.js
> +	const bytes = window.atob(base64.split(',')[1]);
Danger usage.

2020-07-19 12:56 UTC, LitoMore commented on src/utils/image-compression.js
> +	return _blob;
Unnecessary underscore.

2020-07-24 04:11 UTC, LitoMore requested changes

2020-07-24 04:11 UTC, LitoMore commented on src/utils/image-compression.js
> +export const compress = (base64, quality, mimeType, MAX_WIDTH) => {
maxWidth

2020-08-13 04:03 UTC, LitoMore approved these changes

2020-08-13 04:03 UTC, merged